# Day 6 : House Prices Train Dataset for ML training

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

df = pd.read_csv('train.csv')

## Question 1

In [47]:
x = df[['OverallQual','GrLivArea','GarageCars']].copy()
y = df['SalePrice']
print(x.shape)
print(y.shape)

(1460, 3)
(1460,)

## Question 2

In [48]:
missing_val = x.isna().sum().reset_index().rename(columns={'index':'Feature',0:'Missing_Count'})
print("No, Linear Regression cannot handle NaNs as it would affect the calcualtions and introduce possible inf values")
missing_val

No, Linear Regression cannot handle NaNs as it would affect the calcualtions and introduce possible inf values

       Feature  Missing_Count
0  OverallQual              0
1    GrLivArea              0
2   GarageCars              0

## Question 3

In [49]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(1168, 3)
(292, 3)

## Question 4

In [50]:
model = LinearRegression()
model.fit(X_train,y_train)
print(model.coef_)
print(model.intercept_)
print("\nI dont remember the importance of coefficients but i do rememeber something called the coefficient matrix in linear algebra. Are these correlation coefficients??")
print("Correlation coefficients disctate how highly correlated the features are to the target. This shows the amount of influence a feature has on the prediction of the model for the given target")

[26772.48983385    47.2285051  22239.45989805]
-94208.72140326074

I dont remember the importance of coefficients but i do rememeber something called the coefficient matrix in linear algebra. Are these correlation coefficients??
Correlation coefficients disctate how highly correlated the features are to the target. This shows the amount of influence a feature has on the prediction of the model for the given target

## Question 5

In [51]:
y_pred = model.predict(X_test)
predictions = pd.DataFrame({
    'Actual' : y_test,
    'Predicted': y_pred
    })
predictions.iloc[:10]

      Actual      Predicted
892   154500  139105.720944
1105  325000  288283.257433
413   115000  132683.550804
522   159000  189493.369881
1036  315500  289972.245056
614    75500   42635.196145
218   311500  229962.126193
1160  146000  179669.840820
649    84500   42635.196145
887   135500  127682.495267

## Question 6

In [61]:
mae = mean_absolute_error(y_true=y_test, y_pred=y_pred)
rmse = root_mean_squared_error(y_true=y_test, y_pred=y_pred)
model1_r2 = r2_score(y_true=y_test, y_pred=y_pred)

print(f"MAE = {mae}\nRMSE = {rmse}\nR2 Score = {r2}")

MAE = 28121.524151747955
RMSE = 43032.15048041462
R2 Score = 0.7585805446926186

## Question 7

In [53]:
residual = y_test - y_pred
print(f"1. Residual Mean = {residual.mean()}")
print(f"2. Largest Positive Residual = {residual.max()}")
print(f"3. Largest Negative Residula = {residual.min()}")
print("\nPositive residual to my understanding means the value by which the prediction fell short of the actual value.")

1. Residual Mean = 4815.57059907707
2. Largest Positive Residual = 310927.2153633209
3. Largest Negative Residula = -88733.75409423784

Positive residual to my understanding means the value by which the prediction fell short of the actual value.

## Question 8

In [54]:
coeff_df = pd.DataFrame({
    'Feature' : x.columns,
    'Coeff' : model.coef_
})
coeff_df['Abs Coeff'] = abs(coeff_df['Coeff'])
coeff_df.sort_values(by='Abs Coeff', ascending=False, inplace=True)

print("OverallQual appears most influential.")
coeff_df

OverallQual appears most influential.

       Feature         Coeff     Abs Coeff
0  OverallQual  26772.489834  26772.489834
2   GarageCars  22239.459898  22239.459898
1    GrLivArea     47.228505     47.228505

## Question 9

In [86]:
x_new = pd.concat([x,df[['YearBuilt','TotalBsmtSF']]],axis=1)

X_new_train,X_new_test,y_new_train,y_new_test = train_test_split(x_new, y, test_size=0.2, random_state=42)

model2 = LinearRegression()
model2.fit(X_new_train,y_new_train)

y_new_pred = model2.predict(X_new_test)

model2_r2 = r2_score(y_true=y_new_test,y_pred=y_new_pred)
mae2 = mean_absolute_error(y_true=y_new_test,y_pred=y_new_pred)
print(f"MAE = {mae2}")
print(f"Model 1 R2 = {model1_r2}\nModel 2 R2 = {model2_r2}")
print("\nYes the performance improved because we gave the models\n" \
"more context by adding 2 new features into the training set. " \
"\nWith more context the model can predict better results, " \
"\nthus too little features is also bad for a predictive model.")

MAE = 25414.725402851927
Model 1 R2 = 0.7585805446926186
Model 2 R2 = 0.7938653966356556

Yes the performance improved because we gave the models
more context by adding 2 new features into the training set.
With more context the model can predict better results,
thus too little features is also bad for a predictive model.

## Question 10

1. The model is showing an R2 score of about 79% which is a decent score for a prediction model.
2. It is 79% accurate in predicting the target variable which is way better than a coinflip (50%)
3. Although it will not be completely accurate we can see that the average deviation from the actual value is of about 25400. So we should keep that in mind as a buffer while making decisions.
4. Since the model is not 100% accurate, we may come across some values which may be misleading so we should be cautious about that.
5. We could improve out model by adding more features or creating more features which would help the model predict better outputs by giving it more context.

## Daily DSA Challenge

In [89]:
nums = [2,7,11,15]
target = 9

left = 0
right = left+1

for i in range(len(nums)):
    if nums[left]+nums[right]==target:
        print([left,right])
    else:
        right+=1   
    left+=1

print("1. O(n)^2")
print("2. O(n)")
print("3. Two Pointer")

[0, 1]
1. O(n)^2
2. O(n)
3. Two Pointer

In [91]:
## DSA CORRECTION

nums = [2,7,11,15]
target = 9

seen={}

for i, num in enumerate(nums):
    complement = target - num
    if complement in seen:
        print([seen[complement],i])
    seen[num] = i

## Basically it is iterating over a number and then checking if the complement of that number is in the dict.

[0, 1]