# Day 4 : OList Customers Dataset

In [1]:
import pandas as pd
import numpy as np

customers = pd.read_csv("olist_customers_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")

## Question 1

In [82]:
datasets = [orders,order_items,customers,products]
names = ['orders','order_items','customers','products']
count = 0
summary = pd.DataFrame()
for dataset in datasets:
    summary_dict = {
        "Dataset": names[count],
        "Rows": dataset.shape[0],
        'Columns': dataset.shape[1],
        'Missing values': dataset.isna().sum().sum() ## len(dataset.dropna()) ## Correction
    }
    count+=1
    temp = pd.DataFrame([summary_dict])
    summary = pd.concat([summary,temp], ignore_index=True)


summary

# I took some help for syntax

       Dataset    Rows  Columns  Missing values
0       orders   99441        8            4908
1  order_items  112650        7               0
2    customers   99441        5               0
3     products   32951        9            2448

## Question 2

In [31]:
first_merge = pd.merge(orders,customers, on='customer_id', how='left')
first_merge.head()
print(f"1. Rows = {first_merge.shape[0]}")
print(f"2. Row count did not change")
print(f"3. Because the rows in both dfs were the same before, on joining, the it retains all the rows as it is mapped to customer_id")

1. Rows = 99441
2. Row count did not change
3. Because the rows in both dfs were the same before, on joining, the it retains all the rows as it is mapped to customer_id

## Question 3

In [36]:
top_10_by_state = first_merge.groupby('customer_state').agg(number_of_customers = ('customer_id','count')).reset_index().sort_values('number_of_customers', ascending=False).iloc[:10]
top_10_by_state

   customer_state  number_of_customers
25             SP                41746
18             RJ                12852
10             MG                11635
22             RS                 5466
17             PR                 5045
23             SC                 3637
4              BA                 3380
6              DF                 2140
7              ES                 2033
8              GO                 2020

## Question 4

In [46]:
revenue = round(order_items['price'].sum(),2)
avg_price = round(order_items['price'].mean(),2)
highest_price = order_items['price'].max()

print(f"1. Total Revenue = {revenue}")
print(f"2. Avg Price = {avg_price}")
print(f'3. Highest Price = {highest_price}')

1. Total Revenue = 13591643.7
2. Avg Price = 120.65
3. Highest Price = 6735.0

## Question 5

In [55]:
status = orders.groupby('order_status').agg(count = ('order_status','count')).reset_index().sort_values(by='count', ascending=False)
print(status)
print(f"\n1. Most common = {status['order_status'].iloc[0]}")
print(f"\n1. Leas common = {status['order_status'].iloc[-1]}")

  order_status  count
3    delivered  96478
6      shipped   1107
1     canceled    625
7  unavailable    609
4     invoiced    314
5   processing    301
2      created      5
0     approved      2

1. Most common = delivered

1. Leas common = approved

## Question 6

In [ ]:
merged_order_table = pd.merge(orders, order_items, on='order_id', how='left')
print(f"1. Total Rows after merge = {merged_order_table.shape[0]}")
print(f"2. Because in a left join, it not only retains all the rows from the previous df but also adds the relevant rows form the new df")
## Correction: One order could have multiple items, so the number of rows increased after the merge. One to Many join

1. Total Rows after merge = 113425
2. Because in a left join, it not only retains all the rows from the previous df but also adds the relevant rows form the new df

## Question 7

In [70]:
items_merge = pd.merge(order_items, products, on='product_id', how='left')
items_merge.groupby('product_category_name').agg(total_revenue=('price','sum')).reset_index().sort_values(by='total_revenue', ascending=False).iloc[:10]

     product_category_name  total_revenue
11            beleza_saude     1258681.34
66      relogios_presentes     1205005.68
13         cama_mesa_banho     1036988.68
32           esporte_lazer      988048.97
44  informatica_acessorios      911954.32
54        moveis_decoracao      729762.49
26              cool_stuff      635290.85
72   utilidades_domesticas      632248.66
8               automotivo      592720.11
40      ferramentas_jardim      485256.46

## Question 8

In [78]:
customer_orders = customers.merge(orders, on='customer_id', how='left').merge(order_items, on='order_id', how='left')
customer_orders.groupby('customer_unique_id').agg(total_spent = ('price','sum')).reset_index().sort_values(by='total_spent',ascending=False).iloc[:20]

                     customer_unique_id  total_spent
3826   0a0a92112bd4c708ca5fde585afaa872     13440.00
81962  da122df9eeddfedc1dc1f5349a1a690c      7388.00
44447  763c8b1c9c68a0229c42c9fc6f662b93      7160.00
82808  dc4802a71eae9be1dd28f5d788ceb526      6735.00
26205  459bef486812aa25204be022145caa62      6729.00
95806  ff4159b92c40ebe40454e3e6a7c35ed6      6499.00
24121  4007669dec559734d6f53e029e360987      5934.60
89688  eebb5dda148d3893cdaf5b5ca3040ccb      4690.00
35070  5d0a2980b292d049061542014e8960bf      4599.90
27441  48e1ac109decbb87765a3eade6854098      4590.00
60913  a229eba70ec1c2abef51f04987deb7a5      4400.00
89385  edde2314c6c30e864a128ac95d6b2112      4399.87
93998  fa562ef24d41361e476e748681810e1e      4099.99
75269  c8460e4251689ba205045f3ea17884a1      4080.00
75984  ca27f3dac28fb1063faddd424c9d95fa      4059.00
2032   055ec572ac7f3c7bdd04a183830ebe59      3999.98
426    011875f0176909c5cf0b14a9138bb691      3999.90
89420  edf81e1f3070b9dac83ec83dacdbb9bc      3999.00
35581  5e713be0853d8986528d7869a0811d2b      3980.00
90302  f0767ae738c3d90e7b737d7b8b8bb4d1      3930.00

## Question 9

In [ ]:
print("Well i used left joins everywhere so that i had all the information from the initial df as well as the new df")

"""
Correction:
orders + customers : Keep all orders even if customer info is missing (left join)
order_items + products : Keep all sales record even if product metadata is unavailable (left join)
customers + orders : keep all customers even if they have not placed any orders (left join)
"""

Well i used left joins everywhere so that i had all the information from the initial df as well as the new df

'\nCorrection:\norders + customers : Keep all orders even if customer info is missing\n'

## Question 10

In [81]:
customer_orders.groupby('customer_state').agg(revenue=('price','sum')).reset_index().sort_values(by='revenue',ascending=False).iloc[:10]

   customer_state     revenue
25             SP  5202955.05
18             RJ  1824092.67
10             MG  1585308.03
22             RS   750304.02
17             PR   683083.76
23             SC   520553.34
4              BA   511349.99
6              DF   302603.94
8              GO   294591.95
7              ES   275037.31