# DAY 3 : Video Game Sales

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("vgsales.csv")

## Question 1

In [12]:
print(f"Total Rows = {df.shape[0]}")
print(f"Total Columns = {df.shape[1]}\n")

summary_table = pd.DataFrame({
    "Data Type" : df.dtypes,
    "Missing Values Count" : df.isna().sum()
})

print(summary_table)

Total Rows = 16598
Total Columns = 11

             Data Type  Missing Values Count
Rank             int64                     0
Name            object                     0
Platform        object                     0
Year           float64                   271
Genre           object                     0
Publisher       object                    58
NA_Sales       float64                     0
EU_Sales       float64                     0
JP_Sales       float64                     0
Other_Sales    float64                     0
Global_Sales   float64                     0

## Question 2

In [20]:
sorted_df = df.sort_values(by="Global_Sales", ascending=False)
cols = ['Rank', 'Name', 'Platform', 'Global_Sales']
top_10 = sorted_df[cols].iloc[:10]
top_10

   Rank                       Name Platform  Global_Sales
0     1                 Wii Sports      Wii         82.74
1     2          Super Mario Bros.      NES         40.24
2     3             Mario Kart Wii      Wii         35.82
3     4          Wii Sports Resort      Wii         33.00
4     5   Pokemon Red/Pokemon Blue       GB         31.37
5     6                     Tetris       GB         30.26
6     7      New Super Mario Bros.       DS         30.01
7     8                   Wii Play      Wii         29.02
8     9  New Super Mario Bros. Wii      Wii         28.62
9    10                  Duck Hunt      NES         28.31

## Question 3

In [29]:
publisher_analysis = df.groupby("Publisher").agg(Total_Global_Sales = ("Global_Sales","sum"))
top_10_publishers = publisher_analysis.sort_values(by="Total_Global_Sales", ascending=False).iloc[:10]
print(top_10_publishers)

                              Total_Global_Sales
Publisher
Nintendo                                 1786.56
Electronic Arts                          1110.32
Activision                                727.46
Sony Computer Entertainment               607.50
Ubisoft                                   474.72
Take-Two Interactive                      399.54
THQ                                       340.77
Konami Digital Entertainment              283.64
Sega                                      272.99
Namco Bandai Games                        254.09

## Question 4

In [55]:
platform_analysis = df.groupby("Platform").agg(
    Number_of_Games = ("Name",'count'),
    Total_Global_Sales = ("Global_Sales",'sum')
).reset_index()
platform_analysis = platform_analysis.sort_values(by='Total_Global_Sales', ascending=False)
print(platform_analysis)

   Platform  Number_of_Games  Total_Global_Sales
16      PS2             2161             1255.64
28     X360             1265              979.96
17      PS3             1329              957.84
26      Wii             1325              926.71
4        DS             2163              822.49
15       PS             1196              730.66
6       GBA              822              318.50
19      PSP             1213              296.28
18      PS4              336              278.10
13       PC              960              258.82
29       XB              824              258.26
5        GB               98              255.45
11      NES               98              251.07
2       3DS              509              247.46
10      N64              319              218.88
23     SNES              239              200.05
7        GC              556              199.36
30     XOne              213              141.06
0      2600              133               97.08
27     WiiU              143               81.86
20      PSV              413               61.93
21      SAT              173               33.59
8       GEN               27               28.36
3        DC               52               15.97
22      SCD                6                1.87
12       NG               12                1.44
25       WS                6                1.42
24     TG16                2                0.16
1       3DO                3                0.10
9        GG                1                0.04
14     PCFX                1                0.03

## Question 5

In [40]:
regional_sales = pd.DataFrame({
    "Region" : ['NA','EU','JP','Other'],
    "Total_Sales" : [df['NA_Sales'].sum(), df["EU_Sales"].sum(), df["JP_Sales"].sum(), df["Other_Sales"].sum()]
})

print(regional_sales)
print("\nNA generates most revenue")

  Region  Total_Sales
0     NA      4392.95
1     EU      2434.13
2     JP      1291.02
3  Other       797.75

NA generates most revenue

## Question 6

In [42]:
genre_performance = df.groupby("Genre").agg(
    Avg_Global_Sales = ("Global_Sales","mean"),
    Total_Global_Sales = ("Global_Sales",'sum')
)
genre_performance.sort_values(by='Total_Global_Sales', ascending=False, inplace=True)

print(genre_performance)

              Avg_Global_Sales  Total_Global_Sales
Genre
Action                0.528100             1751.18
Sports                0.567319             1330.93
Shooter               0.791885             1037.37
Role-Playing          0.623233              927.37
Platform              0.938341              831.37
Misc                  0.465762              809.96
Racing                0.586101              732.04
Fighting              0.529375              448.91
Simulation            0.452364              392.20
Puzzle                0.420876              244.95
Adventure             0.185879              239.04
Strategy              0.257151              175.12

## Question 7

In [58]:
platform_based_genre = df.groupby(["Platform","Genre"]).agg(Total_Global_Sales = ("Global_Sales",'sum')).reset_index()
top_15 = platform_based_genre.sort_values(by="Total_Global_Sales", ascending=False)

print(top_15.iloc[:15])

    Platform         Genre  Total_Global_Sales
153      PS3        Action              307.88
244      Wii        Sports              292.06
266     X360       Shooter              278.55
151      PS2        Sports              273.41
141      PS2        Action              272.76
258     X360        Action              242.67
237      Wii          Misc              221.06
161      PS3       Shooter              196.04
147      PS2        Racing              156.28
268     X360        Sports              139.12
37        DS          Misc              137.76
163      PS3        Sports              135.56
43        DS    Simulation              132.03
129       PS        Action              127.05
41        DS  Role-Playing              126.85

## Question 8

In [96]:
platform_game_rank = df.groupby(["Platform","Name"])['Global_Sales'].idxmax().reset_index()
platform_game_rank   # Im unable to figure this one out

## Answer
idx = df.groupby("Platform")['Global_Sales'].idxmax()
result = df.loc[idx,["Platform", 'Name', 'Global_Sales']]
print(result)

      Platform                                    Name  Global_Sales
89        2600                                 Pac-Man          7.81
12635      3DO                             Policenauts          0.06
32         3DS                     Pokemon X/Pokemon Y         14.35
637         DC                         Sonic Adventure          2.42
6           DS                   New Super Mario Bros.         30.01
4           GB                Pokemon Red/Pokemon Blue         31.37
25         GBA           Pokemon Ruby/Pokemon Sapphire         15.85
107         GC                 Super Smash Bros. Melee          7.07
143        GEN                    Sonic the Hedgehog 2          6.03
13525       GG            Sonic the Hedgehog 2 (8-bit)          0.04
46         N64                          Super Mario 64         11.89
1          NES                       Super Mario Bros.         40.24
6681        NG                      Samurai Shodown II          0.25
83          PC                              The Sims 3          8.11
14556     PCFX      Blue Breaker: Ken Yorimo Hohoemi o          0.03
52          PS                            Gran Turismo         10.95
17         PS2           Grand Theft Auto: San Andreas         20.81
16         PS3                      Grand Theft Auto V         21.40
33         PS4               Call of Duty: Black Ops 3         14.24
90         PSP  Grand Theft Auto: Liberty City Stories          7.72
713        PSV                               Minecraft          2.25
888        SAT                        Virtua Fighter 2          1.93
1261       SCD                                Sonic CD          1.50
18        SNES                       Super Mario World         20.61
9223      TG16                              Doukyuusei          0.14
3931        WS                           Final Fantasy          0.51
0          Wii                              Wii Sports         82.74
108       WiiU                            Mario Kart 8          6.96
15        X360                      Kinect Adventures!         21.82
79          XB                                  Halo 2          8.49
101       XOne               Call of Duty: Black Ops 3          7.30

## Question 9

In [102]:
print(f"1. Missing Values :\n{df.isna().sum()}")
# print(f"2. Total loss of rows if used dropna : {df.isna().sum().max()}")
## Correction
print(f"2. Total loss of rows if used dropna : {len(df)-len(df.dropna())}")
# print(f"3. Percentage of dataset loss : {round((df.isna().sum().max())*100/len(df),4)}")
## Correction
print(f"3. Percentage of dataset loss : {round((len(df)-len(df.dropna()))*100/len(df),4)}")

1. Missing Values :
Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64
2. Total loss of rows if used dropna : 307
3. Percentage of dataset loss : 1.8496

## Question 10

In [93]:
eligible_publishers = df.groupby("Publisher").agg(Game = ("Name","count"), Avg_Global_Sales = ("Global_Sales","mean")).reset_index()
eligible_publishers = eligible_publishers[eligible_publishers['Game']>20]
highest_avg_sale = eligible_publishers.drop("Game", axis=1).sort_values(by='Avg_Global_Sales', ascending=False).iloc[:10]
highest_avg_sale

                       Publisher  Avg_Global_Sales
359                     Nintendo          2.541337
323       Microsoft Game Studios          1.300476
66            Bethesda Softworks          1.156901
144             Enix Corporation          1.124667
466                   SquareSoft          1.108654
288                    LucasArts          0.970444
494         Take-Two Interactive          0.967409
456  Sony Computer Entertainment          0.889458
138              Electronic Arts          0.821850
529        Universal Interactive          0.772609