# Day 8 : ML and DSA Foundation

In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

df = pd.read_csv('train.csv')

## Question 1 - Data Prep

In [58]:
X = df[['Pclass','Age','Fare','SibSp','Parch']].copy()
y = df['Survived'].copy()

X['Median_Age'] = X.groupby('Pclass')['Age'].transform('median')
X['Age'].fillna(X['Median_Age'],inplace=True)
print(X.isna().sum())
X.drop(columns=['Median_Age'],inplace=True)

Pclass        0
Age           0
Fare          0
SibSp         0
Parch         0
Median_Age    0
dtype: int64

## Question 2 - Train Test Split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(712, 5)
(179, 5)

In [60]:
X_train

     Pclass   Age      Fare  SibSp  Parch
331       1  45.5   28.5000      0      0
733       2  23.0   13.0000      0      0
382       3  32.0    7.9250      0      0
704       3  26.0    7.8542      1      0
813       3   6.0   31.2750      4      2
..      ...   ...       ...    ...    ...
106       3  21.0    7.6500      0      0
270       1  37.0   31.0000      0      0
860       3  41.0   14.1083      2      0
435       1  14.0  120.0000      1      2
102       1  21.0   77.2875      0      1

[712 rows x 5 columns]

## Question 3 - Decision Tree Classifier

In [61]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

## Question 4 - Predictions

In [62]:
y_pred = model.predict(X_test)
y_true = np.array(y_test)
predictions = pd.DataFrame({'Actual':y_true, 'Predicted':y_pred})
predictions

     Actual  Predicted
0         1          0
1         0          0
2         0          1
3         1          1
4         1          0
..      ...        ...
174       0          0
175       0          0
176       1          0
177       1          0
178       1          1

[179 rows x 2 columns]

## Question 5 - Evaluation

In [63]:
acc = accuracy_score(y_true,y_pred)
precision = precision_score(y_true,y_pred)
recall = recall_score(y_true,y_pred)
f1 = f1_score(y_true,y_pred)

evaluation = pd.DataFrame({
    'Metric': ['Accuracy','Precision','Recall','F1'],
    'Value' : [acc,precision,recall,f1]
})

evaluation

      Metric     Value
0   Accuracy  0.653631
1  Precision  0.590909
2     Recall  0.527027
3         F1  0.557143

## Question 6 - Compare Models

1. Logistic Regression performs better with better Accuracy and Precision. Although Decision Tree Classifier has a slightly better recall (~0.02 more).
2. (searched up differences) Basically Decision Tree Classifiers are majorly affected by noise in the data so it is very important to select the right features to train the model.

**Corrections**

Decision trees capture non linear relationships whereas logistic regressiion only captures linear relationships between features and log odds of survival.

## Question 7 - Feature Importance

In [64]:
feature_importance = model.feature_importances_
cols = X.columns
feature_importance_df = pd.DataFrame({
    'Features' : cols,
    'Importance' : feature_importance
})

feature_importance_df.sort_values(by='Importance', ascending=False, inplace=True)
feature_importance_df

  Features  Importance
2     Fare    0.384152
1      Age    0.380755
0   Pclass    0.122696
3    SibSp    0.074168
4    Parch    0.038229

1. Fare is the most important feature as per the feature importance function of Decision Tree Classifier.
2. The dataset used on Day 5 is a completely different one but I'm guessing the correlation analysis analyses how much the feature influences the target due to correlation. Whereas this one might be a different way of calculating feature important, im not sure.

## Question 8 - Overfitting Experiment

In [65]:
model_2 = DecisionTreeClassifier(max_depth=None)
model_2.fit(X_train,y_train)
test_pred = model_2.predict(X_test)
train_pred = model_2.predict(X_train)

train_acc = accuracy_score(np.array(y_train), train_pred)
test_acc = accuracy_score(np.array(y_test), test_pred)

print(f"Train Accuracy = {train_acc}")
print(f"Test Accuracy = {test_acc}")

Train Accuracy = 0.9592696629213483
Test Accuracy = 0.6536312849162011

Yes, it clearly shows overfitting as the model is showing a 96% accuracy on the training data while only showing about 66% on the test data. This tells us that the model is memorised the training data and thus cannot predict results for an outside test set.

## Question 9 - Controlling Overfitting

In [67]:
model_3 = DecisionTreeClassifier(max_depth=3)
model_3.fit(X_train,y_train)

test_pred = model_3.predict(X_test)
train_pred = model_3.predict(X_train)

train_acc = accuracy_score(np.array(y_train), train_pred)
test_acc = accuracy_score(np.array(y_test), test_pred)

print(f"Train Accuracy = {train_acc}")
print(f"Test Accuracy = {test_acc}")

Train Accuracy = 0.7331460674157303
Test Accuracy = 0.7039106145251397

Yes, restricting depth helped because if the decision tree is too deep then it memorizes the training data instead of learning general patterns.

## Question 10 - Data Science Thinking

1. We can use Decision Trees when we need more interpretability as Logistic Regression is less interpretable of the two.
2. Logistic Regression is less prone to overfitting than a Decision Tree. Decision trees need to be tailored with parameters to avoid overfitting.
3. Logistic regression is robust to noise in the data whereas a decision tree is highly affected by it and will need additional preprocessing.
4. When we have a small dataset, decision trees are better to use as they can be trained on smaller datasets and still perform well. Whereas for logistic regression we need to have a big enough dataset to train the model properly.

---

# DSA Foundation Day 1

## DSA Question 1 - Dictionary Frequency Counter

In [ ]:
word = 'mississippi'

freq = {}

# I had to revisit yesterdays answer for this just for a littl hint

for char in word:
    freq[char] = freq.get(char,0)+1
print(freq)

{'m': 1, 'i': 4, 's': 4, 'p': 2}

## DSA Question 2 - Duplicate Detection

In [69]:
nums = [1,2,3,4,5,2]

nums_set = set(nums)

if len(nums) == len(nums_set):
    print(False)
else:
    print(True)

True

## DSA Question 3 - First Unique Character

In [75]:
word = 'leetcode'

freq = {}

for char in word:
    freq[char] = freq.get(char,0)+1
print(freq)

for key in freq:
    if freq[key] ==1:
        print(key)
        break

{'l': 1, 'e': 3, 't': 1, 'c': 1, 'o': 1, 'd': 1}
l

## DSA Question 4 - Time Complexity

Lookup complexity of dict is O(n) and for set is also O(n)
<br>
**Correction**
<br>
Dict lookup = Avg O(1)
<br>
Set lookup = AVg O(1)

Sets are used to filter out duplicate values
<br>
Dict have key value pairs which help traversing and storing data